import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { io } from 'socket.io-client'
import { useState } from 'react';

// 後で環境変数で設定
const socket = io("http://localhost:5001", {
  withCredentials: true,
});

const Home: NextPage = () => {
  const [message, setMessage] = useState<string>("");
  const [list, setList] = useState<string[]>([]);

  const handleSendMessage = () => {
    // サーバーへ送信
    socket.emit("send_message", { message: message });
    setMessage("");
  };

  // サーバーから受信
  socket.on("received_message", (data) => {
    console.log(data);
    setList([...list, data]);
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Next chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h2>Next chat</h2>
        <div className={styles.chatInputButton}>
          <input type="text" placeholder='メッセージ・・・' onChange={(e) => setMessage(e.target.value)} value={ message } />
          <button onClick={()=>handleSendMessage()} >送信</button>
        </div>
        {list.map((chat: any) => {
          <div className={styles.chatArea} key={chat.message} >
            { chat.message }
          </div>
        })}
      </div>
    </div>
  )
}

export default Home
